services:
  - type: web
    name: youtube-downloader
    env: python
    plan: free
    pythonVersion: "3.9"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: FLASK_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
